### PR TITLE
Convert module to Typescript

### PR DESCRIPTION
**Pull request by benhjames**
I was kind of in two minds about what to do with:

```ts
let permittedPolicies: string;
if ('permittedPolicies' in options) {
  permittedPolicies = options.permittedPolicies as string;
} else {
  permittedPolicies = DEFAULT_PERMITTED_POLICIES;
}
```

Changing it to:

```ts
const { permittedPolicies = DEFAULT_PERMITTED_POLICIES } = options;
```

Would no longer throw an error for `crossdomain({ permittedPolicies: undefined })` (instead using the default).

I figured all breaking changes are undesirable, so I left it as it was. One for the future?

### CODE REVIEW

**Comment by EvanHahn** [comment]
Yeah—I think we should be pretty conservative about breaking changes, just in case.

At a glance, I don't think I understand the breaking change you're talking about, though. Could you explain further?

(I'll give this a more thorough review soon.)

**Comment by benhjames** [comment]
Sure, here's the behaviour for calling `crossdomain({ permittedPolicies: undefined })` in the two ways:

The old way:

- `if ('permittedPolicies' in options) {` evaluates to `true`
- `permittedPolicies` is set to `undefined`
- `if (ALLOWED_POLICIES.indexOf(permittedPolicies) === -1) {` evaluates to `true`
- error thrown!

The new way:

- `options.permittedPolicies` is `undefined`, so set `permittedPolicies` to `DEFAULT_PERMITTED_POLICIES` thanks to default destructuring value
- `if (ALLOWED_POLICIES.indexOf(permittedPolicies) === -1) {` evaluates to `false`
- no error thrown!

Granted, in practice, no-one would likely be doing `crossdomain({ permittedPolicies: undefined })`, instead doing `crossdomain()`, but I suppose in its technicality, that'd be a breaking change.

**Comment by EvanHahn** [comment]
Ah, okay—that's clear. And yeah, I think it's best to avoid a breaking change, even a small one.

I'll plan to take another look at this PR soon.

**Comment by EvanHahn** [comment]
This has been released in `helmet-crossdomain@0.4.0`. Thanks!

**Pull request merged**
